version: '3.8'

services:
  apache_php_mysql:
    build: .
    container_name: projecte0
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:9.3
    environment:
      MYSQL_ROOT_PASSWORD: password1234
      MYSQL_USER: usuari
      MYSQL_PASSWORD: paraula
      LANG: C.UTF-8
    volumes:
      - ./db_data:/var/lib/mysql
      - ./db_init:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    ports:
      - "8081:8080"
    depends_on:
      - db